name: retsept_cherno
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.2.1
  firebase_database: ^11.0.4
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  dio: ^5.5.0+1
  json_serializable: ^6.8.0
  build_runner: ^2.4.12
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  go_router: ^14.2.3
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10+1


  easy_stepper: ^0.8.5+1
  share_plus: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
